"""add app_settings table

Revision ID: 85814553f2d0
Revises: 7552cb3916d0
Create Date: 2026-08-25 17:53:19.436623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85814553f2d0'
down_revision = '7552cb3916d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
